# -*- coding: utf-8 -*-
"""datanext.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_GcSham7uDfeCAebqQNSBKRANR3p3HX
"""

import numpy as np
import re
from scipy.io import wavfile
from scipy import signal
from IPython.display import Audio
import os 
import sys
import pickle

testfile = sys.argv[1]

with open("pickle_model.pkl", 'rb') as file:
    kmeans = pickle.load(file)

sr, data = wavfile.read(testfile)

k = np.array(data).reshape(-1,1)
labels = kmeans.predict(k).tolist()
x = [list(x) for x in zip(data, labels)]
for item in x:
  if item[1] == 0:
    item[0] = 0
final = [i[0] for i in x]

final = np.array(final, dtype='int16')
wavfile.write(filename='newfile.wav', rate=16000, data=final)
